
//token validation
GET http://localhost:5000/auth/validate 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY

###
//login
POST http://localhost:5000/auth/login 
Content-Type: application/json

{
    "email": "danishdavis@hotmail.com",
    "password":"11111"
}

###
//register
POST http://localhost:5000/auth/register 
Content-Type: application/json

{
    "firstname":"Prabin",
    "lastname":"Gyawali",
    "email": "prabin@hotmail.com",
    "password":"11111"
}

###
//getProject by teamID.
GET http://localhost:5000/api/projects/byTeamId/605117e72900ec3aecef3ebc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE2NTczZTZjZDI0MjdiNDNkOTc1OCIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkLzRPTWJZWUE3dzFabGs1aW16U3hmZTJGSXRsckUyOXZnaGJmeVRaYlFkME4uQVdTR1lpeFMiLCJpYXQiOjE2MTU5NDcxMzR9.7LRb1p3-5d9HDFcX-_lIU1z-kzImH9hhlJjBXZ1RZXA
Content-Type: application/json

###
//getProject by projectID.
GET http://localhost:5000/api/projects/byProjectId/605171ebb02c251a30726b4d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE2NTczZTZjZDI0MjdiNDNkOTc1OCIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkLzRPTWJZWUE3dzFabGs1aW16U3hmZTJGSXRsckUyOXZnaGJmeVRaYlFkME4uQVdTR1lpeFMiLCJpYXQiOjE2MTU5NDcxMzR9.7LRb1p3-5d9HDFcX-_lIU1z-kzImH9hhlJjBXZ1RZXA
Content-Type: application/json

###
//getAllProjects
GET http://localhost:5000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYWJpbkBneWF3YWxpLmNhIiwicGFzc3dvcmQiOiIkMmIkMTAkWk5SUlpIZmp1V2JXa0Jwa2V5bnAvLktPVHhlZ3EzU2l4aldEMVpXTlhmeXpKTG1ZTVpSSUsiLCJpYXQiOjE2MTU4Mjc4MDZ9.PNmrTQ43SKbpsE_5mV9dCxivH2gB1q8HauY04xmzn4s
Content-Type: application/json

###
//add project
POST http://localhost:5000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE2NTczZTZjZDI0MjdiNDNkOTc1OCIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkLzRPTWJZWUE3dzFabGs1aW16U3hmZTJGSXRsckUyOXZnaGJmeVRaYlFkME4uQVdTR1lpeFMiLCJpYXQiOjE2MTU5NDcxMzR9.7LRb1p3-5d9HDFcX-_lIU1z-kzImH9hhlJjBXZ1RZXA
Content-Type: application/json

{
  "name": "Test",
  "description": "This is a new project",
  "team_id":"605117e72900ec3aecef3ebc"
}


###
//add Team
POST http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTExZmEwYjViMWY4MThlMDc3YjM3ZCIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCREQUR2dHNxdUJsOFlQcGx1TVppaVd1MVkyajFqVlhKSGptVjhMemxXNklQOXhOZnR2ZTBBRyIsImlhdCI6MTYxNTkyOTI4OX0.MpSql7cei26aLTPixj5lQDkFgQZjOU2JJukIpwM9jQA
Content-Type: application/json

{
  "name": "Team Namastee",
  "description": "This is a new Team"
}

###
//get all teams
GET http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTExZmEwYjViMWY4MThlMDc3YjM3ZCIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCREQUR2dHNxdUJsOFlQcGx1TVppaVd1MVkyajFqVlhKSGptVjhMemxXNklQOXhOZnR2ZTBBRyIsImlhdCI6MTYxNTkyOTI4OX0.MpSql7cei26aLTPixj5lQDkFgQZjOU2JJukIpwM9jQA
Content-Type: application/json

###
//get team by id
GET http://localhost:5000/api/teams/605172848f100c6aa0aa6a35
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE2MDA2OTQ1fQ.mwt4dAEoYkQsRFsC9eJ4miS9nenGd9Wzy9iEgBr2F9A
Content-Type: application/json


###
//join a teams
PUT http://localhost:5000/api/teams/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE2NTczZTZjZDI0MjdiNDNkOTc1OCIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkLzRPTWJZWUE3dzFabGs1aW16U3hmZTJGSXRsckUyOXZnaGJmeVRaYlFkME4uQVdTR1lpeFMiLCJpYXQiOjE2MTU5NDcxMzR9.7LRb1p3-5d9HDFcX-_lIU1z-kzImH9hhlJjBXZ1RZXA
Content-Type: application/json

{
  "teamName": "Team Namastee",
  "teamId": "605117e72900ec3aecef3ebc"
}

###
//join to a project
PUT http://localhost:5000/api/projects/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY
Content-Type: application/json

{
  "projectId": "605171ebb02c251a30726b4d"
}

###
// Create Sprint
POST http://localhost:5000/api/sprints
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTExZmEwYjViMWY4MThlMDc3YjM3ZCIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCREQUR2dHNxdUJsOFlQcGx1TVppaVd1MVkyajFqVlhKSGptVjhMemxXNklQOXhOZnR2ZTBBRyIsImlhdCI6MTYxNTkyOTI4OX0.MpSql7cei26aLTPixj5lQDkFgQZjOU2JJukIpwM9jQA
Content-Type: application/json

{
  "name": "Trial",
  "description": "Trial",
  "project_id": "605359188c7e743434c68140",
  "sprint_id": "6077a5eaad05e11e043c716c",
  "user_stories" :[{"_id": "6077a153516e427cf4bb5471", "estimated_time": "4,0", "moveto_backlog":false}]
}

###
// Get Sprint by project
GET http://localhost:5000/api/sprints/byProjectId/605359188c7e743434c68140
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE2MDA2OTQ1fQ.mwt4dAEoYkQsRFsC9eJ4miS9nenGd9Wzy9iEgBr2F9A
Content-Type: application/json

###
// Get All Sprints by project
GET http://localhost:5000/api/sprints/allByProjectId/605359188c7e743434c68140
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE2MDA2OTQ1fQ.mwt4dAEoYkQsRFsC9eJ4miS9nenGd9Wzy9iEgBr2F9A
Content-Type: application/json

###
// Complete Sprint
POST http://localhost:5000/api/sprints/completeSprint/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTExZmEwYjViMWY4MThlMDc3YjM3ZCIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCREQUR2dHNxdUJsOFlQcGx1TVppaVd1MVkyajFqVlhKSGptVjhMemxXNklQOXhOZnR2ZTBBRyIsImlhdCI6MTYxNTkyOTI4OX0.MpSql7cei26aLTPixj5lQDkFgQZjOU2JJukIpwM9jQA
Content-Type: application/json

{
  "sprint_id": "60563ba05b07252c34b99162"
}

###
// Generate Sprint report
GET http://localhost:5000/api/sprints/generateReport
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTExZmEwYjViMWY4MThlMDc3YjM3ZCIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCREQUR2dHNxdUJsOFlQcGx1TVppaVd1MVkyajFqVlhKSGptVjhMemxXNklQOXhOZnR2ZTBBRyIsImlhdCI6MTYxNTkyOTI4OX0.MpSql7cei26aLTPixj5lQDkFgQZjOU2JJukIpwM9jQA
Content-Type: application/json

{
  "sprint_id": "607b24af850a1f6e9409cc67"
}

### 
// Create User Story
POST http://localhost:5000/api/userstories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE4MzU0MDAzfQ.QwhtThwtRbK7EEIQnnM145ypeTSeBqGjOF8_wNBUKbA
Content-Type: application/json

{
  "title": "April",
  "description": "take a few cows as well, they seem friendly",
  "assigned_to": "60517062190eda5ea84387e1",
  "estimated_time": "1,0",
  "parent_task": null,
  "sprint_id": "6060c32f31adb50ae86fead8",
  "project_id": "6052856377cb3e545caeb3af",
  "identifier": "MA-1"
}

###
// Get User Story by id
GET http://localhost:5000/api/userstories/byTaskId/6062a54d3dd2c61bf46f3128
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE3Mjg4NzE0fQ.TyheHG6p9LAbBdU39s0mKX0bRv0NjjIUoR57zmKA074
Content-Type: application/json

###
// Get User Stories by Sprint
GET http://localhost:5000/api/userstories/bySprint/6077a123516e427cf4bb546f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE3Mjg4NzE0fQ.TyheHG6p9LAbBdU39s0mKX0bRv0NjjIUoR57zmKA074
Content-Type: application/json


###
// Get unfinished User Stories by Sprint
GET http://localhost:5000/api/userstories/unfinishedTask/6060d8e431adb50ae86fead9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE4NDUyMjM0fQ.Yso-Ssi998WOZFIKau56F58l0Tq-3v_BePzo1nI9rGw
Content-Type: application/json



###
// Update User Story
PUT http://localhost:5000/api/userstories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE3Mjg4NzE0fQ.TyheHG6p9LAbBdU39s0mKX0bRv0NjjIUoR57zmKA074
Content-Type: application/json

{
    "_id": "6062a54d3dd2c61bf46f3128",
    "title": "Breaking Bad",
    "desctiption": "Walking Dead",
    "assigned_to": "60517062190eda5ea84387e1",
    "estimated_time": "11,30",
    "time_spent": "1,0",
    "moveto_backlog": true
}


###
// Get User Stories by State
// %20 to encode a space
GET http://localhost:5000/api/userstories/byState/to%20do
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE2MDA2OTQ1fQ.mwt4dAEoYkQsRFsC9eJ4miS9nenGd9Wzy9iEgBr2F9A
Content-Type: application/json

###
// Get User Stories by Assigned To
GET http://localhost:5000/api/userstories/byAssignedTo/60517062190eda5ea84387e1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE2MDA2OTQ1fQ.mwt4dAEoYkQsRFsC9eJ4miS9nenGd9Wzy9iEgBr2F9A
Content-Type: application/json

###
// Get User Stories by Parent Task 
GET http://localhost:5000/api/userstories/byParentTask/60564281b3be2e0b90f02d46
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE2MDA2OTQ1fQ.mwt4dAEoYkQsRFsC9eJ4miS9nenGd9Wzy9iEgBr2F9A
Content-Type: application/json

###
// Assign a developer to a user story
PUT http://localhost:5000/api/userstories/assignTask
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY
Content-Type: application/json

{
  "id": "605171ebb02c251a30726b4d",
  "assigned_to": 
}

###
// Change state of user story
PUT http://localhost:5000/api/userstories/changeState
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY
Content-Type: application/json

{
  "id": "60563f44086c5d40c4a49606",
  "state": "done"
}

###
// change the estimated time of a user story
PUT http://localhost:5000/api/userstories/changeEstimatedTime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY
Content-Type: application/json

{
  "id": "60563f44086c5d40c4a49606",
  "estimated_time": "5 seconds"
}

###
// add time spent on a User Story
PUT http://localhost:5000/api/userstories/addTime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY
Content-Type: application/json

{
  "id": "60563f44086c5d40c4a49606",
  "time_spent": "5 seconds"
}


###
// Change description of a user story
PUT http://localhost:5000/api/userstories/updateDescription
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY
Content-Type: application/json

{
  "id": "60563f44086c5d40c4a49606",
  "description": "The cows are stonger than we originally assumed."
}

###
// Change title of a user story
PUT http://localhost:5000/api/userstories/updateTitle
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY
Content-Type: application/json

{
  "id": "60563f44086c5d40c4a49606",
  "title": "Destroy all cows!"
}

