###
//register
POST http://localhost:5000/auth/register 
Content-Type: application/json

{
    "firstname": "Prabin",
    "lastname": "Gyawali",
    "email": "prabin@hotmail.com",
    "password": "password"
}


###
//token validation
GET http://localhost:5000/auth/validate 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODRkNGU2MWJiZjQ3Mjk3ODVkMzhhZSIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwiZmlyc3RuYW1lIjoiUHJhYmluIiwibGFzdG5hbWUiOiJHeWF3YWxpIiwiaWF0IjoxNjE5MzE4MDEwfQ.AwT928mT-UUoCLlyHXt-L1klnSQGZNoK_YQO7wOiFmI
Content-Type: application/json


###
//login
POST http://localhost:5000/auth/login 
Content-Type: application/json

{
    "email": "prabin@hotmail.com",
    "password":"password"
}