
###
//register
POST http://localhost:5000/auth/register 
Content-Type: application/json

{
    "firstname":"Prabin",
    "lastname":"Gyawali",
    "email": "prabin@hotmail.com",
    "password":"11111"
}



//token validation
GET http://localhost:5000/auth/validate 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDdkYjY1ODI4Yzk4NTRiMGE3MzUzNiIsImVtYWlsIjoicHJhYmluQGd5YXdhbGkuY2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYLnA4RWNoLjkxYk9PTzZFTHhpWXplZVpQZTFHWmtIck5pT282VVc3ejRLNUZyTDhzb2NvZSIsImlhdCI6MTYxNTkyNDM4M30.xDTsVYQtwh0pnFhSovncHROXCpHsS-rQTswjKqVPkhY



###
//login
POST http://localhost:5000/auth/login 
Content-Type: application/json

{
    "email": "prabin@hotmail.com",
    "password":"11111"
}