

###
//add project
POST http://localhost:5000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE2NTczZTZjZDI0MjdiNDNkOTc1OCIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkLzRPTWJZWUE3dzFabGs1aW16U3hmZTJGSXRsckUyOXZnaGJmeVRaYlFkME4uQVdTR1lpeFMiLCJpYXQiOjE2MTU5NDcxMzR9.7LRb1p3-5d9HDFcX-_lIU1z-kzImH9hhlJjBXZ1RZXA
Content-Type: application/json

{
  "name": "Test",
  "description": "This is a new project",
  "team_id":"605117e72900ec3aecef3ebc"
}

###
//getProject by teamID.
GET http://localhost:5000/api/projects/byTeamId/605117e72900ec3aecef3ebc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE2NTczZTZjZDI0MjdiNDNkOTc1OCIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkLzRPTWJZWUE3dzFabGs1aW16U3hmZTJGSXRsckUyOXZnaGJmeVRaYlFkME4uQVdTR1lpeFMiLCJpYXQiOjE2MTU5NDcxMzR9.7LRb1p3-5d9HDFcX-_lIU1z-kzImH9hhlJjBXZ1RZXA
Content-Type: application/json


###
//getProject by projectID.
GET http://localhost:5000/api/projects/byProjectId/605171ebb02c251a30726b4d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE2NTczZTZjZDI0MjdiNDNkOTc1OCIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkLzRPTWJZWUE3dzFabGs1aW16U3hmZTJGSXRsckUyOXZnaGJmeVRaYlFkME4uQVdTR1lpeFMiLCJpYXQiOjE2MTU5NDcxMzR9.7LRb1p3-5d9HDFcX-_lIU1z-kzImH9hhlJjBXZ1RZXA
Content-Type: application/json




