
### 
// Update user password
PUT http://localhost:5000/api/users/change_password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODRkNGU2MWJiZjQ3Mjk3ODVkMzhhZSIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwiZmlyc3RuYW1lIjoiUHJhYmluIiwibGFzdG5hbWUiOiJHeWF3YWxpIiwiaWF0IjoxNjE5MzE4MDEwfQ.AwT928mT-UUoCLlyHXt-L1klnSQGZNoK_YQO7wOiFmI
Content-Type: application/json

{
  "old_password": "pass123s4",
  "new_password": "password"
}


###
//get all users
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODRkNGU2MWJiZjQ3Mjk3ODVkMzhhZSIsImVtYWlsIjoicHJhYmluQGhvdG1haWwuY29tIiwiZmlyc3RuYW1lIjoiUHJhYmluIiwibGFzdG5hbWUiOiJHeWF3YWxpIiwiaWF0IjoxNjE5MzE4MDEwfQ.AwT928mT-UUoCLlyHXt-L1klnSQGZNoK_YQO7wOiFmI
Content-Type: application/json
