
###
// Get backlogs for a specific project
GET http://localhost:5000/api/userstories/backlogs/6052856377cb3e545caeb3af
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTE3MDYyMTkwZWRhNWVhODQzODdlMSIsImVtYWlsIjoiZGFuaXNoZGF2aXNAaG90bWFpbC5jb20iLCJmaXJzdG5hbWUiOiJEYW5pc2giLCJsYXN0bmFtZSI6IkRhdmlzIiwiaWF0IjoxNjE3Mjg4NzE0fQ.TyheHG6p9LAbBdU39s0mKX0bRv0NjjIUoR57zmKA074
Content-Type: application/json

